### ISSUE TITLE
Error when rebuilding SiteOrigin Premium

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/plugin-build#3]
If you run `build:release` for a second time in [SiteOrigin Premium](https://github.com/siteorigin/siteorigin-premium/), it triggers the following error

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, lstat '/Users/gpriday/Dropbox/Sites/dev/wp-content/plugins/siteorigin-premium/dist/siteorigin-premium/addons/plugin/contact-form-fields/fields/js/pikaday.min.js'
    at Error (native)
```

This might have something to do with the build config. I wasn't able to figure that out. Either deleting the `dist` folder, or running the `clean` task fixes the issue. I tried adding a clean task before `build:release`, but that doesn't seem to fix the issue.

**Comment by braamgenis** [comment]
The problem was dist and tmp folders not being ignored in build-config.js for SO Premium.
