### ISSUE TITLE
Build folder is included in dist folder for SiteOrigin Premium

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/plugin-build#4]
This also might have something to do with the build config in [SiteOrigin Premium](https://github.com/siteorigin/siteorigin-premium/), but for some reason the build folder is included in the dist folder. [This line](https://github.com/siteorigin/siteorigin-premium/blob/develop/build-config.js#L30) should be excluding it.

**Comment by braamgenis** [comment]
The problem was `dist` and `tmp` folders not being ignored in `build-config.js` for SO Premium.
