### ISSUE TITLE
.pot file: Correct build date

### ISSUE THREAD

**Issue by Misplon** [siteorigin/plugin-build#7]
At the moment the `.pot` file build date prints as follows:

`"PO-Revision-Date: 2018-MO-DA HO:MI+ZONE\n"`

If possible, let's get the month and day printing.

**Comment by braamgenis** [comment]
This was fixed by updating the `gulp-wp-pot` package to the latest version in 6d8f3cba0ae7cbba52b43a98cd40890a87301e10 which doesn't seem to generate a date header anymore. Hopefully this sorts out the issues we've been having with GlotPress.
